version: "2"
linters:
  enable:
    - exhaustive
    - godot
    - misspell
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: cmd/main.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/coderflexx/blog-api
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
